
--8. Remplir toutes les tables par les instances fournies en annexe (compléter les données d’évaluation).

-- insertion sans association
INSERT into hotel values(
    thotel(1 ,    
    'Renaissance' ,  
    'Tlemcen',    
     5,    
     NULL,    
     t_set_ref_chambre(),    
     t_set_ref_evaluation() )
    );


INSERT into hotel values(thotel(2, 'Seybouse', 'Annaba', 3,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(3, 'Hôtel Novotel', 'Constantine' ,4,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(4, 'Saint George d''Alger', 'Alger', 5,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(5, 'Ibis Alger Aéroport', 'Alger', 2,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(6, 'El Mountazah Annaba' ,'Annaba', 3,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(7, 'Hôtel Albert 1er', 'Alger', 3,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(8, 'Chems', 'Oran', 2,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(9, 'Colombe', 'Oran', 3,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(10, 'Mercure' ,'Alger' ,4,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(11, 'Le Méridien', 'Oran' ,5,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));
INSERT into hotel values(thotel(12, 'Hôtel Sofitel', 'Alger', 5,NULL,t_set_ref_chambre(),t_set_ref_evaluation() ));

--TABLEEEE CLIENTT 



INSERT INTO CLIENT  VALUES	(tclient	(1	,'	BOUROUBI'	,'	Taous'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(2	,'	BOUZIDI'	,'	AMEL'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(3	,'	LACHEMI'	,'	Bouzid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(4	,'	BOUCHEMLA'	,'	Elias'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(5	,'	HADJ'	,'	Zouhir'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(6	,'	OUSSEDIK'	,'	Hakim'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(7	,'	AAKOUB'	,'	Fatiha'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(8	,'	ABAD'	,'	Abdelhamid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(9	,'	ABADA'	,'	Mohamed'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(10	,'	ABAYAHIA'	,'	Abdelkader'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(11	,'	ABBACI'	,'	Abdelmadjid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(12	,'	ABBAS'	,'	Samira'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(13	,'	ABBOU'	,'	Mohamed'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(14	,'	ABDELAZIZ'	,'	Ahmed'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(15	,'	ABDELMOUMEN'	,'	Nassima'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(16	,'	ABDELOUAHAB'	,'	OUAHIBA'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(17	,'	ABDEMEZIANE'	,'	Madjid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(18	,'	ABERKANE'	,'	Aicha'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(19	,'	AZOUG'	,'	Dalila'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(20	,'	BENOUADAH'	,'	Mohammed'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(21	,'	ACHAIBOU'	,'	Rachid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(22	,'	ADDAD'	,'	Fadila'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(23	,'	AGGOUN'	,'	Khadidja'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(24	,'	AISSAT'	,'	Salima'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(25	,'	AMARA'	,'	Dahbia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(26	,'	AROUEL'	,'	Leila'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(27	,'	BAALI'	,'	Souad'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(28	,'	BABACI'	,'	Mourad'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(29	,'	BACHA'	,'	Nadia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(30	,'	BAHBOUH'	,'	Naima'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(31	,'	BADI'	,'	Hatem'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(32	,'	BAKIR'	,'	ADEL'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(33	,'	BALI'	,'	Malika'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(34	,'	BASSI'	,'	Fatima'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(35	,'	BEHADI'	,'	Youcef'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(36	,'	BEKKAT'	,'	Hadia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(37	,'	BELABES'	,'	Abdelkader'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(38	,'	BELAKERMI'	,'	Mohammed'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(39	,'	BELGHALI'	,'	Mohammed'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(40	,'	BELHAMIDI'	,'	Mustapha'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(41	,'	BELKACEMI'	,'	Hocine'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(42	,'	BELKOUT'	,'	Tayeb'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(43	,'	RAHALI'	,'	Ahcene'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(44	,'	FERAOUN'	,'	Houria'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(45	,'	TERKI'	,'	Amina'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(46	,'	CHAOUI'	,'	Farid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(47	,'	BENDALI'	,'	Hacine'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(48	,'	CHAKER'	,'	Nadia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(49	,'	BELHAMIDI'	,'	Mustapha'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(50	,'	BELKACEMI'	,'	Hocine'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(51	,'	BELKOUT'	,'	Tayeb'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(52	,'	RAHALI'	,'	Ahcene'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(53	,'	FERAOUN'	,'	Houria'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(54	,'	TERKI'	,'	Amina'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(55	,'	CHAOUI'	,'	Farid'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(56	,'	BENDALI'	,'	Hacine'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(57	,'	CHAKER'	,'	Nadia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(58	,'	BOULARAS'	,'	Fatima'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(59	,'	IGOUDJIL'	,'	Redouane'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(60	,'	GHEZALI'	,'	Lakhdar'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(61	,'	KOULA'	,'	Brahim'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(62	,'	BELAID'	,'	Layachi'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(63	,'	CHALABI'	,'	Mourad'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(64	,'	MOHAMMEDI'	,'	Mustapha'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(65	,'	FEKAR'	,'	Abdelaziz'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(66	,'	SAIDOUNI'	,'	Wafa'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(67	,'	Yalaoui'	,'	Lamia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(68	,'	AYATA'	,'	Samia'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);
INSERT INTO CLIENT  VALUES	(tclient	(69	,'	TEBIBEL'	,'	Nabila'	,	NULL,	t_set_ref_reservation(),		t_set_ref_evaluation())	);

-- TABLE CHAMBRE


INSERT INTO 	CHAMBRE 	VALUES(tchambre	(1	,	2	,	1	,'	simple'	,	4500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(1	,	4	,	0	,'	autre'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(1	,	5	,	0	,'	triple'	,	7000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(1	,	6	,	1	,'	double'	,	6000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(1	,	9	,	1	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(1	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(2	,	2	,	1	,'	simple'	,	4800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(2	,	5	,	1	,'	simple'	,	4000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(2	,	6	,	1	,'	double'	,	6000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(2	,	9	,	1	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(2	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(3	,	2	,	1	,'	double'	,	7100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(3	,	5	,	1	,'	double'	,	5500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(3	,	6	,	1	,'	double'	,	6000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(3	,	9	,	1	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(3	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(4	,	2	,	1	,'	simple'	,	5400	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(4	,	6	,	2	,'	double'	,	6200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(4	,	9	,	2	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(4	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(5	,	2	,	2	,'	double'	,	8600	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(5	,	6	,	2	,'	double'	,	6200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(5	,	9	,	2	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(5	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(6	,	2	,	2	,'	simple'	,	5800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(6	,	6	,	2	,'	double'	,	6200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(6	,	9	,	2	,'	double'	,	4800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(6	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(7	,	2	,	2	,'	simple'	,	5800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(7	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(8	,	2	,	2	,'	double'	,	8600	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(8	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(9	,	2	,	3	,'	suite'	,	16000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(9	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(10	,	1	,	1	,'	simple'	,	7100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(10	,	2	,	3	,'	suite'	,	16500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(10	,	7	,	1	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(10	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(11	,	1	,	1	,'	simple'	,	7100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(11	,	4	,	1	,'	simple'	,	8400	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(11	,	7	,	1	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(11	,	11	,	0	,'	simple'	,	7800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(12	,	1	,	1	,'	double'	,	8800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(12	,	4	,	1	,'	simple'	,	8400	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(12	,	7	,	1	,'	double'	,	4200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(12	,	11	,	0	,'	double'	,	9100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(13	,	1	,	1	,'	simple'	,	6200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(13	,	4	,	1	,'	simple'	,	8600	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(13	,	11	,	0	,'	double'	,	9100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(14	,	4	,	1	,'	simple'	,	9000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(14	,	11	,	1	,'	double'	,	9100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(15	,	11	,	1	,'	double'	,	9100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(16	,	11	,	1	,'	simple'	,	7700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(17	,	11	,	1	,'	simple'	,	7700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(18	,	11	,	1	,'	simple'	,	7700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(19	,	11	,	1	,'	simple'	,	7700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(20	,	1	,	2	,'	double'	,	9000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(20	,	7	,	2	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(20	,	11	,	1	,'	simple'	,	7700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(21	,	1	,	2	,'	simple'	,	6800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(21	,	4	,	2	,'	double'	,	12000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(21	,	7	,	2	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(21	,	11	,	1	,'	simple'	,	7500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(22	,	1	,	2	,'	simple'	,	6800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(22	,	4	,	2	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(22	,	7	,	2	,'	double'	,	4200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(22	,	11	,	1	,'	simple'	,	7500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(23	,	1	,	2	,'	double'	,	8900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(23	,	11	,	1	,'	simple'	,	7500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(24	,	11	,	1	,'	double'	,	8000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(25	,	11	,	1	,'	double'	,	8000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(26	,	11	,	1	,'	double'	,	8000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(27	,	11	,	2	,'	triple'	,	10900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(28	,	11	,	2	,'	triple'	,	10900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(29	,	11	,	2	,'	simple'	,	7200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(30	,	7	,	3	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(30	,	11	,	2	,'	simple'	,	7200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(31	,	4	,	3	,'	triple'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(31	,	7	,	3	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(31	,	11	,	2	,'	simple'	,	7200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(32	,	4	,	3	,'	simple'	,	9000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(32	,	7	,	3	,'	double'	,	4200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(32	,	11	,	2	,'	simple'	,	7200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(33	,	13	,	3	,'	simple'	,	5000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(40	,	7	,	4	,'	simple'	,	2000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(41	,	7	,	4	,'	simple'	,	2000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(42	,	7	,	4	,'	simple'	,	2000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(43	,	7	,	4	,'	simple'	,	1800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(44	,	7	,	4	,'	simple'	,	1800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(100	,	8	,	1	,'	simple'	,	2900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(100	,	10	,	1	,'	double'	,	9700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(101	,	3	,	1	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(101	,	8	,	1	,'	simple'	,	2900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(101	,	10	,	1	,'	double'	,	11000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(101	,	12	,	1	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(102	,	3	,	1	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(102	,	8	,	1	,'	simple'	,	2800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(102	,	12	,	1	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(103	,	3	,	1	,'	simple'	,	3300	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(103	,	12	,	1	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(104	,	12	,	1	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(105	,	12	,	1	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(106	,	12	,	1	,'	double'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(107	,	12	,	1	,'	double'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(200	,	8	,	2	,'	simple'	,	2800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(200	,	10	,	2	,'	double'	,	9700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(201	,	3	,	2	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(201	,	8	,	2	,'	simple'	,	2900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(201	,	10	,	2	,'	double'	,	9700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(201	,	12	,	2	,'	double'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(202	,	3	,	2	,'	simple'	,	3200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(202	,	8	,	2	,'	simple'	,	2900	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(202	,	10	,	2	,'	triple'	,	14100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(202	,	12	,	2	,'	double'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(203	,	3	,	2	,'	simple'	,	3300	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(203	,	12	,	2	,'	double'	,	11800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(204	,	12	,	2	,'	double'	,	11800	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(205	,	12	,	2	,'	double'	,	13000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(206	,	12	,	2	,'	double'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(207	,	12	,	2	,'	double'	,	14500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(208	,	14	,	1	,'	simple'	,	4500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(300	,	8	,	3	,'	simple'	,	3000	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(301	,	3	,	3	,'	simple'	,	3400	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(301	,	8	,	3	,'	simple'	,	3100	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(301	,	12	,	3	,'	suite'	,	19500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(302	,	3	,	3	,'	simple'	,	3400	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(302	,	8	,	3	,'	double'	,	3700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(302	,	12	,	3	,'	suite'	,	19500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(303	,	3	,	3	,'	simple'	,	3400	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(303	,	12	,	3	,'	suite'	,	19500	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(401	,	3	,	4	,'	double'	,	4200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(401	,	8	,	4	,'	double'	,	3700	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(402	,	3	,	4	,'	double'	,	4200	,NULL,t_set_ref_reservation())	);
INSERT INTO 	CHAMBRE 	VALUES(tchambre	(402	,	8	,	4	,'	simple'	,	2000	,NULL,t_set_ref_reservation())	);
--table reservation
---------------------------------------------------------------------------------------

INSERT INTO reservation VALUES	(treservation	(1	,'	11/05/2022	     ','	15/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(2	,'	11/04/2022	     ','	18/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(3	,'	05/04/2022	     ','	06/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(4	,'	27/04/2022	     ','	01/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(5	,'	11/06/2022	     ','	14/06/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(6	,'	02/05/2022	     ','	10/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(7	,'	28/04/2022	     ','	01/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(8	,'	12/05/2022	     ','	13/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(9	,'	04/05/2022	     ','	09/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(10	,'	30/04/2022	     ','	03/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(11	,'	13/04/2022	     ','	14/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(12	,'	01/05/2022	     ','	03/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(13	,'	03/05/2022	     ','	20/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(14	,'	15/04/2022	     ','	20/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(15	,'	09/05/2022	     ','	10/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(16	,'	06/04/2022	     ','	08/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(17	,'	07/05/2022	     ','	12/05/2006	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(18	,'	04/04/2022	     ','	08/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(19	,'	07/04/2022	     ','	07/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(20	,'	07/05/2022	     ','	12/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(21	,'	11/04/2022	     ','	14/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(22	,'	01/05/2022	     ','	05/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(23	,'	09/05/2022	     ','	13/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(24	,'	04/04/2022	     ','	05/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(25	,'	07/06/2022	     ','	10/06/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(26	,'	22/04/2022	     ','	26/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(27	,'	04/04/2022	     ','	08/04/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(28	,'	12/05/2022	     ','	10/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(29	,'	04/05/2022	     ','	09/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(30	,'	04/04/2022	     ','	06/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(31	,'	17/05/2022	     ','	23/05/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(32	,'	27/05/2022	     ','	02/06/2022	   ',	NULL,	NULL));
INSERT INTO reservation VALUES	(treservation	(33	,'	11/05/2022	     ','	18/05/2022	   ',	NULL,	NULL));

--evaluation

INSERT INTO EVALUATION  VALUES        (tevaluation	(1	    ,'	11/05/2022	    ',	5	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(2	    ,'	11/04/2022	    ',	3	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(3	    ,'	05/04/2022	    ',	4	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(4	    ,'	27/04/2022	    ',	2	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(5	    ,'	11/06/2022	    ',	3	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(6	    ,'	02/05/2022	    ',	5	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(7	    ,'	28/04/2022	    ',	6	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(8	    ,'	12/05/2022	    ',	7	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(9	    ,'	04/05/2022	    ',	8	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(10	    ,'	30/04/2022	    ',	1	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(11	    ,'	13/04/2022	    ',	3	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(12	    ,'	01/05/2022	    ',	5	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(13	    ,'	03/05/2022	    ',	6	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(14	    ,'	15/04/2022	    ',	10	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(15	    ,'	09/05/2022	    ',	9	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(16	    ,'	06/04/2022	    ',	5	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(17	    ,'	07/05/2022	    ',	7	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(18	    ,'	04/04/2022	    ',	3	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(19	    ,'	07/04/2022	    ',	8	,	NULL,	NULL));
INSERT INTO EVALUATION  VALUES        (tevaluation	(20	    ,'	07/05/2022	    ',	4	,	NULL,	NULL));


UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)
	WHERE NUMHOTEL =	2	AND numchambre =	1	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	1	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	5	)	WHERE NUMHOTEL =	5	AND numchambre =	1	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	6	)	WHERE NUMHOTEL =	6	AND numchambre =	1	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	9	)	WHERE NUMHOTEL =	9	AND numchambre =	1	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	1	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	2	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	5	)	WHERE NUMHOTEL =	5	AND numchambre =	2	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	6	)	WHERE NUMHOTEL =	6	AND numchambre =	2	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	9	)	WHERE NUMHOTEL =	9	AND numchambre =	2	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	2	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	3	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	5	)	WHERE NUMHOTEL =	5	AND numchambre =	3	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	6	)	WHERE NUMHOTEL =	6	AND numchambre =	3	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	9	)	WHERE NUMHOTEL =	9	AND numchambre =	3	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	3	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	4	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	6	)	WHERE NUMHOTEL =	6	AND numchambre =	4	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	9	)	WHERE NUMHOTEL =	9	AND numchambre =	4	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	4	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	5	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	6	)	WHERE NUMHOTEL =	6	AND numchambre =	5	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	9	)	WHERE NUMHOTEL =	9	AND numchambre =	5	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	5	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	6	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	6	)	WHERE NUMHOTEL =	6	AND numchambre =	6	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	9	)	WHERE NUMHOTEL =	9	AND numchambre =	6	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	6	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	7	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	7	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	8	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	8	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	9	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	9	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	10	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	2	)	WHERE NUMHOTEL =	2	AND numchambre =	10	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	10	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	10	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	11	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	11	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	11	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	11	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	12	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	12	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	12	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	12	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	13	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	13	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	13	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	14	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	14	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	15	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	16	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	17	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	18	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	19	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	20	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	20	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	20	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	21	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	21	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	21	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	21	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	22	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	22	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	22	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	22	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	1	)	WHERE NUMHOTEL =	1	AND numchambre =	23	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	23	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	24	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	25	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	26	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	27	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	28	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	29	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	30	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	30	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	31	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	31	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	31	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	4	)	WHERE NUMHOTEL =	4	AND numchambre =	32	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	32	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	11	)	WHERE NUMHOTEL =	11	AND numchambre =	32	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	13	)	WHERE NUMHOTEL =	13	AND numchambre =	33	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	40	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	41	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	42	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	43	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	7	)	WHERE NUMHOTEL =	7	AND numchambre =	44	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	100	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	10	)	WHERE NUMHOTEL =	10	AND numchambre =	100	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	101	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	101	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	10	)	WHERE NUMHOTEL =	10	AND numchambre =	101	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	101	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	102	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	102	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	102	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	103	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	103	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	104	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	105	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	106	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	107	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	200	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	10	)	WHERE NUMHOTEL =	10	AND numchambre =	200	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	201	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	201	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	10	)	WHERE NUMHOTEL =	10	AND numchambre =	201	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	201	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	202	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	202	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	10	)	WHERE NUMHOTEL =	10	AND numchambre =	202	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	202	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	203	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	203	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	204	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	205	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	206	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	207	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	14	)	WHERE NUMHOTEL =	14	AND numchambre =	208	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	300	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	301	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	301	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	301	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	302	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	302	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	302	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	303	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	12	)	WHERE NUMHOTEL =	12	AND numchambre =	303	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	401	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	401	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	3	)	WHERE NUMHOTEL =	3	AND numchambre =	402	;
UPDATE chambre SET chambre_hotel = (SELECT REF(H) FROM HOTEL H WHERE H.NUMHOTEL =	8	)	WHERE NUMHOTEL =	8	AND numchambre =	402	;

INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES
 ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	1	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	1	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	5	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	5	AND c.numchambre =	1	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	6	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	6	AND c.numchambre =	1	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	9	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	9	AND c.numchambre =	1	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	1	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	2	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	5	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	5	AND c.numchambre =	2	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	6	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	6	AND c.numchambre =	2	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	9	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	9	AND c.numchambre =	2	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	2	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	3	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	5	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	5	AND c.numchambre =	3	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	6	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	6	AND c.numchambre =	3	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	9	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	9	AND c.numchambre =	3	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	3	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	4	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	6	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	6	AND c.numchambre =	4	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	9	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	9	AND c.numchambre =	4	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	4	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	5	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	6	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	6	AND c.numchambre =	5	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	9	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	9	AND c.numchambre =	5	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	5	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	6	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	6	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	6	AND c.numchambre =	6	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	9	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	9	AND c.numchambre =	6	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	6	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	7	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	7	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	8	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	8	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	9	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	9	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	10	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	2	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	2	AND c.numchambre =	10	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	10	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	10	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	11	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	11	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	11	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	11	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	12	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	12	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	12	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	12	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	13	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	13	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	13	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	14	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	14	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	15	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	16	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	17	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	18	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	19	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	20	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	20	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	20	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	21	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	21	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	21	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	21	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	22	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	22	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	22	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	22	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	1	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	1	AND c.numchambre =	23	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	23	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	24	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	25	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	26	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	27	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	28	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	29	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	30	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	30	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	31	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	31	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	31	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	4	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	4	AND c.numchambre =	32	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	32	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	11	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	11	AND c.numchambre =	32	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	13	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	13	AND c.numchambre =	33	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	40	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	41	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	42	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	43	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	7	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	7	AND c.numchambre =	44	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	100	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	10	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	10	AND c.numchambre =	100	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	101	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	101	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	10	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	10	AND c.numchambre =	101	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	101	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	102	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	102	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	102	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	103	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	103	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	104	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	105	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	106	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	107	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	200	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	10	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	10	AND c.numchambre =	200	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	201	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	201	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	10	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	10	AND c.numchambre =	201	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	201	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	202	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	202	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	10	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	10	AND c.numchambre =	202	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	202	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	203	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	203	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	204	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	205	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	206	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	207	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	14	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	14	AND c.numchambre =	208	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	300	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	301	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	301	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	301	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	302	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	302	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	302	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	303	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	12	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	12	AND c.numchambre =	303	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	401	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	401	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	3	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	3	AND c.numchambre =	402	));
INSERT INTO TABLE(SELECT H.hotel_chambre FROM HOTEL H WHERE H.NUMHOTEL =	8	) VALUES ( (SELECT REF(c) FROM chambre c WHERE c.NUMHOTEL =	8	AND c.numchambre =	402	));


UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	1	) ,
eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	1	)WHERE NUMEVAL=	1	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	4	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	45	)WHERE NUMEVAL=	2	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	5	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	23	)WHERE NUMEVAL=	3	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	6	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	12	)WHERE NUMEVAL=	4	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	7	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	7	)WHERE NUMEVAL=	5	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	8	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	34	)WHERE NUMEVAL=	6	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	2	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	13	)WHERE NUMEVAL=	7	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	11	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	23	)WHERE NUMEVAL=	8	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	2	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	44	)WHERE NUMEVAL=	9	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	12	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	21	)WHERE NUMEVAL=	10	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	4	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	12	)WHERE NUMEVAL=	11	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	10	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	13	)WHERE NUMEVAL=	12	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	1	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	6	)WHERE NUMEVAL=	13	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	3	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	7	)WHERE NUMEVAL=	14	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	9	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	40	)WHERE NUMEVAL=	15	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	1	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	54	)WHERE NUMEVAL=	16	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	12	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	29	)WHERE NUMEVAL=	17	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	8	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	19	)WHERE NUMEVAL=	18	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	7	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	18	)WHERE NUMEVAL=	19	;
UPDATE evaluation SET eval_hotel = (SELECT REF(h) FROM hotel h WHERE h.NUMHOTEL =	6	) ,eval_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	37	)WHERE NUMEVAL=	20	;


INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	1	) VALUES
 ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	1	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	4	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	2	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	5	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	3	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	6	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	4	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	7	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	5	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	8	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	6	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	2	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	7	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	11	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	8	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	2	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	9	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	12	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	10	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	4	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	11	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	10	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	12	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	1	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	13	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	3	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	14	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	9	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	15	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	1	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	16	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	12	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	17	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	8	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	18	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	7	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	19	));
INSERT INTO TABLE(SELECT h.hotel_evaluation FROM hotel h WHERE h.numhotel =	6	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	20	));


INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	1	) 
VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	1	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	45	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	2	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	23	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	3	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	12	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	4	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	7	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	5	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	34	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	6	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	13	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	7	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	23	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	8	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	44	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	9	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	21	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	10	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	12	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	11	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	13	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	12	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	6	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	13	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	7	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	14	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	40	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	15	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	54	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	16	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	29	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	17	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	19	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	18	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	18	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	19	));
INSERT INTO TABLE(SELECT c.client_eval FROM client c WHERE c.numclient =	37	) VALUES ( (SELECT REF(e) FROM evaluation e WHERE e.numeval =	20	));

INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	1	) VALUES
 ((SELECT REF(r) FROM reservation r WHERE r.numres =	1	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	2	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	2	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	3	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	4	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	5	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	13	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	6	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	14	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	7	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	14	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	8	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	23	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	9	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	28	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	10	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	20	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	11	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	12	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	12	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	7	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	13	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	44	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	14	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	40	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	15	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	40	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	16	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	40	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	17	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	22	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	18	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	112	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	19	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	26	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	20	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	29	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	21	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	37	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	22	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	29	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	23	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	35	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	24	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	35	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	25	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	35	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	26	));
INSERT INTO TABLE(SELECT c.client_res FROM client c WHERE c.numclient =	37	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	27	));


INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	5	)
 VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	1	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	2	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	5	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	1	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	2	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	3	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	30	and c.NUMHOTEL=	7	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	4	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	100	and c.NUMHOTEL=	10	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	5	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	6	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	7	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	21	and c.NUMHOTEL=	4	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	8	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	9	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	3	and c.NUMHOTEL=	9	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	10	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	9	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	11	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	8	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	12	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	7	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	13	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	5	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	14	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	9	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	15	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	8	and c.NUMHOTEL=	2	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	16	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	23	and c.NUMHOTEL=	1	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	17	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	25	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	18	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	5	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	19	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	25	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	20	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	11	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	21	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	302	and c.NUMHOTEL=	8	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	22	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	205	and c.NUMHOTEL=	12	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	23	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	101	and c.NUMHOTEL=	12	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	24	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	25	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	6	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	26	));
INSERT INTO TABLE(SELECT c.chambre_res FROM chambre c WHERE c.numchambre =	202	and c.NUMHOTEL=	12	) VALUES ((SELECT REF(r) FROM reservation r WHERE r.numres =	27	));


UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	5	) ,
res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	1	)WHERE numres=	1	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	2	)WHERE numres=	2	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	6	)WHERE numres=	3	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	30	and c.NUMHOTEL=	7	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	6	)WHERE numres=	4	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	100	and c.NUMHOTEL=	10	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	6	)WHERE numres=	5	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	6	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	13	)WHERE numres=	6	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	6	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	14	)WHERE numres=	7	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	21	and c.NUMHOTEL=	4	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	14	)WHERE numres=	8	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	6	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	23	)WHERE numres=	9	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	3	and c.NUMHOTEL=	9	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	28	)WHERE numres=	10	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	9	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	20	)WHERE numres=	11	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	8	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	12	)WHERE numres=	12	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	7	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	7	)WHERE numres=	13	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	5	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	44	)WHERE numres=	14	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	9	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	40	)WHERE numres=	15	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	8	and c.NUMHOTEL=	2	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	40	)WHERE numres=	16	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	23	and c.NUMHOTEL=	1	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	40	)WHERE numres=	17	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	25	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	22	)WHERE numres=	18	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	5	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	112	)WHERE numres=	19	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	25	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	26	)WHERE numres=	20	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	1	and c.NUMHOTEL=	11	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	29	)WHERE numres=	21	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	302	and c.NUMHOTEL=	8	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	37	)WHERE numres=	22	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	205	and c.NUMHOTEL=	12	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	29	)WHERE numres=	23	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	101	and c.NUMHOTEL=	12	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	35	)WHERE numres=	24	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	5	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	35	)WHERE numres=	25	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	2	and c.NUMHOTEL=	6	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	35	)WHERE numres=	26	;
UPDATE reservation SET res_chambre = (SELECT REF(c) FROM chambre c WHERE c.numchambre =	202	and c.NUMHOTEL=	12	) ,res_client=(SELECT REF(c) FROM client c WHERE c.NUMCLIENT =	37	)WHERE numres=	27	;